Author: Greg Ungerer Date: 2018-11-08 15:10:29 Revision: 39f225dc0ae57e2f52cfcc62c14c121c371663cc Comment: user/netifd: fix use of json is_error()
Compiling netifd with glibc as the library fails with the following
error:

CMakeFiles/netifd.dir/handler.c.o: In function `netifd_parse_script_handler':
handler.c:(.text+0xf4): undefined reference to `is_error'
collect2: error: ld returned 1 exit status
CMakeFiles/netifd.dir/build.make:640: recipe for target 'netifd' failed
make[7]: *** [netifd] Error 1

According to internet sources the use of is_error() is not really
required and it is an ambiguous function name. Better to just check
the NULLness of the return pointer for error indication.

Create a patch to remove use of is_error().